version: '3'
services:
  tensorflow:
    image: navysu/tensorflow-notebook
    ports:
      - "8900:8888"
    restart:
      always
    volumes:
      # notebook for work
      - ./notebooks/work:/home/jovyan/work
      # notebook for myown
      - ./notebooks/mybooks:/home/jovyan/mybooks




