version: '3'
services:
  tensorflow:
    image: navysu/tensorflow-notebook
    ports:
      - "8900:8888"
    restart:
      always
    volumes:
      # notebook for work
      - ./volumes/notebooks/work:/home/jovyan/work
      # notebook for myown
      - ./volumes/notebooks/mybooks:/home/jovyan/mybooks
      # google api tokens
      - ./volumes/google:/google
      # configuration files
      - ./volumes/config/jupyter_notebook_config.json:/home/jovyan/.jupyter/jupyter_notebook_config.json
      - ./volumes/config/nbconfig/common.json:/home/jovyan/.jupyter/nbconfig/common.json
      - ./volumes/config/nbconfig/notebook.json:/home/jovyan/.jupyter/nbconfig/notebook.json

